server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://api:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /swagger-ui/ {
        proxy_pass http://api:8080/swagger-ui/;
    }

    location /v3/api-docs/ {
        proxy_pass http://api:8080/v3/api-docs/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
